<script setup lang="ts">
import { ref } from 'vue'
import { Download, FileUp, Trash2 } from 'lucide-vue-next'
import AppButton from '@/components/ui/AppButton.vue'
import AppCard from '@/components/ui/AppCard.vue'
import AppInput from '@/components/ui/AppInput.vue'
import AppModal from '@/components/ui/AppModal.vue'
import AppPageHeader from '@/components/ui/AppPageHeader.vue'
import { backupRepository, summarizeBackup, validateBackup, type BackupData, type BackupSummary } from '@/repositories/backupRepository'
import { useSettingsStore } from '@/stores/settings'
import { useUiStore } from '@/stores/ui'
import { toDateKey } from '@/utils/date'
const ui=useUiStore(),settings=useSettingsStore(),fileInput=ref<HTMLInputElement>(),pending=ref<BackupData>(),summary=ref<BackupSummary>(),clearOpen=ref(false),clearPhrase=ref(''),busy=ref(false)
async function exportBackup(){busy.value=true;try{const data=await backupRepository.export(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gym-tracker-backup-${toDateKey()}.json`;a.click();URL.revokeObjectURL(url);ui.notify('Backup esportato.','success')}catch{ui.notify('Esportazione non riuscita.','error')}finally{busy.value=false}}
async function selectFile(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{const parsed:unknown=JSON.parse(await file.text());if(!validateBackup(parsed))throw new Error();pending.value=parsed;summary.value=summarizeBackup(parsed)}catch{ui.notify('File non valido o versione non supportata.','error')}finally{(event.target as HTMLInputElement).value=''}}
async function restore(){if(!pending.value)return;busy.value=true;try{await backupRepository.restore(pending.value);await settings.initialize(true);pending.value=undefined;summary.value=undefined;ui.notify('Backup ripristinato.','success')}catch{ui.notify('Ripristino fallito: i dati precedenti sono rimasti invariati.','error')}finally{busy.value=false}}
async function clearAll(){if(clearPhrase.value!=='CANCELLA')return;busy.value=true;try{await backupRepository.clearAll();await settings.initialize(true);clearOpen.value=false;clearPhrase.value='';ui.notify('Tutti i dati sono stati cancellati.','success')}catch{ui.notify('Cancellazione non riuscita.','error')}finally{busy.value=false}}
</script>
<template><div class="page"><AppPageHeader title="Dati" back/><AppCard><section class="data-section"><div><h2>Backup</h2><p>Esporta una copia completa dei tuoi dati o ripristina un backup precedente. L’importazione sostituisce tutti i dati presenti.</p></div><div class="actions"><AppButton :icon="Download" :disabled="busy" @click="exportBackup">Esporta JSON</AppButton><AppButton variant="secondary" :icon="FileUp" :disabled="busy" @click="fileInput?.click()">Importa JSON</AppButton><input ref="fileInput" class="sr-only" type="file" accept="application/json,.json" @change="selectFile"></div></section></AppCard><AppCard><section class="data-section danger-zone"><div><h2>Cancella tutti i dati</h2><p>Elimina definitivamente esercizi, allenamenti e impostazioni da questo dispositivo.</p></div><AppButton variant="danger" :icon="Trash2" @click="clearOpen=true">Cancella tutto</AppButton></section></AppCard><AppModal :open="Boolean(pending)" title="Conferma importazione" @close="pending=undefined"><div v-if="summary" class="summary"><p>Il backup sostituirà interamente i dati presenti.</p><ul><li>{{summary.exercises}} esercizi</li><li>{{summary.weightLogs}} registrazioni pesi</li><li>{{summary.weightSets}} serie</li><li>{{summary.cardioLogs}} registrazioni cardio</li></ul></div><template #footer><AppButton variant="ghost" @click="pending=undefined">Annulla</AppButton><AppButton :disabled="busy" @click="restore">Sostituisci dati</AppButton></template></AppModal><AppModal :open="clearOpen" title="Cancellazione definitiva" @close="clearOpen=false"><div class="stack"><p class="warning">Questa operazione non può essere annullata. Esporta prima un backup se vuoi conservare i dati.</p><AppInput v-model="clearPhrase" label="Scrivi CANCELLA per confermare" autocomplete="off"/></div><template #footer><AppButton variant="ghost" @click="clearOpen=false">Annulla</AppButton><AppButton variant="danger" :disabled="clearPhrase!=='CANCELLA'||busy" @click="clearAll">Cancella definitivamente</AppButton></template></AppModal></div></template>
<style scoped>.data-section{display:grid;gap:var(--space-4)}.data-section h2{margin:0;font-size:var(--text-lg)}.data-section p{margin:var(--space-2) 0 0;color:var(--color-text-muted);line-height:1.55}.actions{display:flex;flex-wrap:wrap;gap:var(--space-3)}.danger-zone{border-left:4px solid var(--color-danger);padding-left:var(--space-3)}.summary p,.warning{margin:0;line-height:1.55}.summary ul{display:grid;gap:var(--space-2);margin-bottom:0}</style>
