<script setup lang="ts">
import { Pencil, Trash2 } from 'lucide-vue-next'
import AppCard from '@/components/ui/AppCard.vue'
import AppIconButton from '@/components/ui/AppIconButton.vue'
import { calculateIntervalTotalSeconds, formatSeconds } from '@/services/cardioIntervals'
import { formatNumber } from '@/utils/number'
import type { CardioLog } from '@/models'
defineProps<{ log: CardioLog }>()
defineEmits<{ delete: [log: CardioLog] }>()
</script>
<template><AppCard><article class="cardio-card"><header><div class="summary"><h2>{{log.exerciseName}}</h2><span aria-hidden="true">|</span><strong v-if="(log.mode??'duration')==='intervals'&&log.interval">{{formatSeconds(calculateIntervalTotalSeconds(log.interval))}}</strong><strong v-else>{{formatNumber(log.minutes)}} min</strong></div><div class="actions"><RouterLink class="edit-link" :to="`/dashboard/cardio/${log.id}/modifica`" aria-label="Modifica registrazione cardio"><Pencil :size="20" aria-hidden="true"/></RouterLink><AppIconButton label="Elimina registrazione cardio" :icon="Trash2" danger @click="$emit('delete',log)"/></div></header><template v-if="(log.mode??'duration')==='intervals'&&log.interval"><p class="interval-title"><strong>{{log.interval.sets}} set</strong> · {{formatSeconds(log.interval.workSeconds)}} lavoro / {{formatSeconds(log.interval.restSeconds)}} pausa · {{formatSeconds(log.interval.restBetweenSetsSeconds)}} tra set</p><ol class="exercise-list"><li v-for="exercise in log.interval.exercises" :key="exercise">{{exercise}}</li></ol></template><p v-if="log.notes" class="notes">{{log.notes}}</p></article></AppCard></template>
<style scoped>.cardio-card header{display:flex;align-items:center;justify-content:space-between;gap:var(--space-2)}.summary{display:flex;align-items:baseline;gap:var(--space-2);min-width:0}.summary h2{margin:0;overflow:hidden;font-size:var(--text-lg);text-overflow:ellipsis;text-transform:uppercase;white-space:nowrap}.summary>span{color:var(--color-border)}.summary>strong{flex:none;font-size:var(--text-lg);font-variant-numeric:tabular-nums}.actions{display:flex;flex:none}.edit-link{width:44px;height:44px;display:grid;place-items:center;color:var(--color-text-muted);border-radius:50%}.interval-title{margin:var(--space-2) 0 0;color:var(--color-text-muted);font-size:var(--text-sm)}.interval-title strong{color:var(--color-text)}.exercise-list{display:flex;gap:var(--space-2);margin:var(--space-2) 0 0;padding:0;overflow-x:auto;list-style:none;scrollbar-width:thin}.exercise-list li{flex:none;padding:4px 8px;border-radius:99px;background:var(--color-primary-soft);color:var(--color-accent-text);font-size:var(--text-xs);font-weight:700}.notes{margin:var(--space-2) 0 0;padding-top:var(--space-2);border-top:1px solid var(--color-border);color:var(--color-text-muted);font-size:var(--text-sm);white-space:pre-wrap}@media(max-width:390px){.summary h2{font-size:var(--text-base)}.summary>strong{font-size:var(--text-base)}} </style>
